### ISSUE TITLE
Error: INSTALLATION FAILED: YAML parse error on streamlit/templates/configmap.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by HWiese1980** [samdobson/helm#2]
Hey, I'm currently trying your streamlit helm chart and I'm running into the error message in the title. 

> Error: INSTALLATION FAILED: YAML parse error on streamlit/templates/configmap.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context

Versions:

* kubectl: 1.23.5
* minikube: 1.25.2
* kubernetes: 1.23.1
* helm: 3.8.1

**Comment by HWiese1980** [comment]
Seems like this is somehow related to Helm 3, see https://github.com/helm/helm/issues/6251

**Comment by samdobson** [comment]
Hi @HWiese1980 ,

I am seeing the same result as you with Helm 3.8.1.

It looks like including data from a file with `--set-file` no longer works.

We could use Helm's `.Files.Get` to replace the current implementation, e.g. by placing `app.py` in the `charts/streamlit/` directory and using the following in `config.yaml`.

```yaml
data:
  streamlit_app.py: |-
    {{ .Files.Get "app.py" | nindent 4 }}
```

... the problem with that approach is, the application code needs to be packaged inside the helm chart itself, which was the very thing this chart was trying to avoid.

I'm not sure what else we can do about this, because helm does not seem to allow external files to be included right now, other than wait for https://github.com/helm/helm/pull/8841 to land...

**Comment by HWiese1980** [comment]
Ah... that's a pity. I'd have loved to just shoot up a StreamLit app in a local cluster. I suppose, we'll have to wait then... Thanks for looking into it though. I'm a complete Helm/K8s noob, so guess I'll not be of much help here.

**Comment by msabramo** [comment]
My error is very similar, but slightly different. I'm guessing it's probably the same problem:

```
$ helm install my-streamlit-app samdobson/streamlit --set-file appCode=main.py
Error: INSTALLATION FAILED: YAML parse error on streamlit/templates/configmap.yaml: error converting YAML to JSON: yaml: line 8: did not find expected key
```

**Comment by samdobson** [comment]
It's far from ideal, but let's use `kubectl` directly to create the configmap. We could do something else, but its probably best to just bypass helm at this point.

@HWiese1980 I've pushed a new change with [87b631f](https://github.com/samdobson/helm/commit/87b631f0b9d32e823c7aefe37ebba77a1d6f236c) that does just this. You'll need to run `helm repo update`, and should be able to follow the guide in https://github.com/samdobson/helm/tree/master/charts/streamlit to deploy your application.

I'm going to close this issue, as it is no longer relevant to the latest chart release, but feel free to open a new one if you bump into something else.

**Comment by HWiese1980** [comment]
I'll go check it out. In case of further problems I'll report back. Thank you very much!

**Comment by HWiese1980** [comment]
Seems to be working. I'll have to figure out how to install additional dependencies though. But that's a different story.
